name: Upload Extension to Store

on:
  release:
    types: [published]

jobs:
  upload-extension:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repository
        uses: actions/checkout@v2

      - name: build-the-extension
        uses: ./.github/actions/build
        with:
          destination-folder: "dist"
          zip-file-name: "extension.zip"
          with-checkout: false

      - name: Upload to Chrome Web Store
        uses: chrome-webstore-upload/action@v1.1.0
        with:
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          source: "dist/extension.zip"
